name : Flask CI/CD Pipeline

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

  

  test:
    runs-on : ubuntu-latest 
    needs : build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name:  Run tests
        run: |
          pytest test.py 

  docker:
    needs : test
    runs-on : ubuntu-latest
    steps: 
      - name : Checkout code
        uses: actions/checkout@v2 

      - name : Login to Docker Hub
        uses: docker/login-action@v2
        with :
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Build and push Docker image 
        run : |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/flask.app:latest .
      

      - name : Run Docker container 
        run: |
          docker run -d -p 5000:5000 --name flask-test ${{secrets.DOCKERHUB_USERNAME}}/flask.app:latest
      - name: Push Docker image
        run: |    
          docker push ${{secrets.DOCKERHUB_USERNAME}}/flask.app:latest 





